// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pay.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChargeRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeRequest) Reset()         { *m = ChargeRequest{} }
func (m *ChargeRequest) String() string { return proto.CompactTextString(m) }
func (*ChargeRequest) ProtoMessage()    {}
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{0}
}

func (m *ChargeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeRequest.Unmarshal(m, b)
}
func (m *ChargeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeRequest.Marshal(b, m, deterministic)
}
func (m *ChargeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeRequest.Merge(m, src)
}
func (m *ChargeRequest) XXX_Size() int {
	return xxx_messageInfo_ChargeRequest.Size(m)
}
func (m *ChargeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeRequest proto.InternalMessageInfo

func (m *ChargeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChargeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChargeRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChargeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ChargeResponse struct {
	Paid                 bool     `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Captured             bool     `protobuf:"varint,3,opt,name=captured,proto3" json:"captured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeResponse) Reset()         { *m = ChargeResponse{} }
func (m *ChargeResponse) String() string { return proto.CompactTextString(m) }
func (*ChargeResponse) ProtoMessage()    {}
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{1}
}

func (m *ChargeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeResponse.Unmarshal(m, b)
}
func (m *ChargeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeResponse.Marshal(b, m, deterministic)
}
func (m *ChargeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeResponse.Merge(m, src)
}
func (m *ChargeResponse) XXX_Size() int {
	return xxx_messageInfo_ChargeResponse.Size(m)
}
func (m *ChargeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeResponse proto.InternalMessageInfo

func (m *ChargeResponse) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *ChargeResponse) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeResponse) GetCaptured() bool {
	if m != nil {
		return m.Captured
	}
	return false
}

func init() {
	proto.RegisterType((*ChargeRequest)(nil), "proto.ChargeRequest")
	proto.RegisterType((*ChargeResponse)(nil), "proto.ChargeResponse")
}

func init() { proto.RegisterFile("proto/pay.proto", fileDescriptor_6e5aad0ac58a7583) }

var fileDescriptor_6e5aad0ac58a7583 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0xb5, 0xbb, 0xac, 0x23, 0x56, 0x18, 0xaa, 0x84, 0x9e, 0x96, 0x3d, 0xf5, 0x54,
	0x41, 0x0f, 0xfe, 0x00, 0xf1, 0x28, 0x48, 0x4e, 0x5e, 0xc7, 0x66, 0xa8, 0x41, 0x9a, 0xc4, 0x24,
	0x7b, 0xe8, 0xd9, 0x3f, 0x2e, 0x4e, 0xaa, 0x74, 0x7b, 0xca, 0x7b, 0x2f, 0x43, 0xde, 0x97, 0x81,
	0xeb, 0x10, 0x7d, 0xf6, 0x77, 0x81, 0xf6, 0x6b, 0x51, 0xd8, 0xc8, 0x31, 0x7c, 0x57, 0x70, 0xf5,
	0xf4, 0x41, 0x71, 0xcb, 0x9a, 0xbf, 0x46, 0x4e, 0x19, 0xe7, 0x50, 0x5b, 0xa3, 0xaa, 0xbe, 0x5a,
	0x35, 0xba, 0xb6, 0x06, 0x17, 0xd0, 0x64, 0xff, 0xc9, 0x4e, 0xd5, 0x7d, 0xb5, 0xba, 0xd0, 0xc5,
	0xe0, 0x2d, 0xb4, 0xb4, 0xf3, 0xa3, 0xcb, 0xea, 0x5c, 0x26, 0x0f, 0x0e, 0x11, 0x66, 0x8e, 0x76,
	0xac, 0x66, 0x32, 0x2c, 0x1a, 0x7b, 0xb8, 0x34, 0x9c, 0x36, 0xd1, 0x86, 0x6c, 0xbd, 0x53, 0x8d,
	0x5c, 0x1d, 0x47, 0xc3, 0x1b, 0xcc, 0xff, 0x20, 0x52, 0xf0, 0x2e, 0xf1, 0xef, 0x3b, 0x81, 0x0e,
	0x1c, 0x9d, 0x16, 0x7d, 0xd4, 0x59, 0x4f, 0x3a, 0x97, 0xd0, 0x6d, 0x28, 0xe4, 0x31, 0xb2, 0x11,
	0x9a, 0x4e, 0xff, 0xfb, 0xfb, 0x67, 0x80, 0x57, 0xda, 0xbf, 0x90, 0xa3, 0x2d, 0x47, 0x7c, 0x84,
	0xb6, 0xf4, 0xe0, 0xa2, 0xac, 0x61, 0x3d, 0xf9, 0xfb, 0xf2, 0xe6, 0x24, 0x2d, 0x30, 0xc3, 0xd9,
	0x7b, 0x2b, 0xf9, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xc6, 0x2a, 0x01, 0x47, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayManagerClient is the client API for PayManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayManagerClient interface {
	Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error)
}

type payManagerClient struct {
	cc *grpc.ClientConn
}

func NewPayManagerClient(cc *grpc.ClientConn) PayManagerClient {
	return &payManagerClient{cc}
}

func (c *payManagerClient) Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error) {
	out := new(ChargeResponse)
	err := c.cc.Invoke(ctx, "/proto.PayManager/Charge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayManagerServer is the server API for PayManager service.
type PayManagerServer interface {
	Charge(context.Context, *ChargeRequest) (*ChargeResponse, error)
}

func RegisterPayManagerServer(s *grpc.Server, srv PayManagerServer) {
	s.RegisterService(&_PayManager_serviceDesc, srv)
}

func _PayManager_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayManagerServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PayManager/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayManagerServer).Charge(ctx, req.(*ChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PayManager",
	HandlerType: (*PayManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _PayManager_Charge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pay.proto",
}
