// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pay.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChargeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Amount               int32    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeRequest) Reset()         { *m = ChargeRequest{} }
func (m *ChargeRequest) String() string { return proto.CompactTextString(m) }
func (*ChargeRequest) ProtoMessage()    {}
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{0}
}

func (m *ChargeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeRequest.Unmarshal(m, b)
}
func (m *ChargeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeRequest.Marshal(b, m, deterministic)
}
func (m *ChargeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeRequest.Merge(m, src)
}
func (m *ChargeRequest) XXX_Size() int {
	return xxx_messageInfo_ChargeRequest.Size(m)
}
func (m *ChargeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeRequest proto.InternalMessageInfo

func (m *ChargeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChargeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChargeRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChargeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ChargeResponse struct {
	Paid                 bool     `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Captured             bool     `protobuf:"varint,3,opt,name=captured,proto3" json:"captured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeResponse) Reset()         { *m = ChargeResponse{} }
func (m *ChargeResponse) String() string { return proto.CompactTextString(m) }
func (*ChargeResponse) ProtoMessage()    {}
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{1}
}

func (m *ChargeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeResponse.Unmarshal(m, b)
}
func (m *ChargeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeResponse.Marshal(b, m, deterministic)
}
func (m *ChargeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeResponse.Merge(m, src)
}
func (m *ChargeResponse) XXX_Size() int {
	return xxx_messageInfo_ChargeResponse.Size(m)
}
func (m *ChargeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeResponse proto.InternalMessageInfo

func (m *ChargeResponse) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *ChargeResponse) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeResponse) GetCaptured() bool {
	if m != nil {
		return m.Captured
	}
	return false
}

func init() {
	proto.RegisterType((*ChargeRequest)(nil), "pb.ChargeRequest")
	proto.RegisterType((*ChargeResponse)(nil), "pb.ChargeResponse")
}

func init() { proto.RegisterFile("proto/pay.proto", fileDescriptor_6e5aad0ac58a7583) }

var fileDescriptor_6e5aad0ac58a7583 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x6d, 0xdc, 0x96, 0x3a, 0xe2, 0x8a, 0x83, 0x48, 0xd8, 0x53, 0xe9, 0x69, 0x4f, 0x15,
	0xf5, 0x07, 0x78, 0xf0, 0x0f, 0x48, 0xbc, 0x78, 0x4d, 0xdb, 0x41, 0x83, 0x6c, 0x32, 0x26, 0xa9,
	0xb0, 0x67, 0xff, 0xb8, 0x38, 0x5d, 0xa5, 0x7b, 0x7b, 0xef, 0x25, 0xcc, 0xfb, 0x66, 0xe0, 0x92,
	0x63, 0xc8, 0xe1, 0x96, 0xed, 0xbe, 0x13, 0x85, 0x8a, 0xfb, 0xf6, 0xbb, 0x80, 0x8b, 0xa7, 0x77,
	0x1b, 0xdf, 0xc8, 0xd0, 0xe7, 0x44, 0x29, 0xe3, 0x1a, 0x94, 0x1b, 0x75, 0xd1, 0x14, 0xdb, 0x33,
	0xa3, 0xdc, 0x88, 0xd7, 0x50, 0xe6, 0xf0, 0x41, 0x5e, 0x2b, 0x89, 0x66, 0x83, 0x37, 0x50, 0xd9,
	0x5d, 0x98, 0x7c, 0xd6, 0xa7, 0x4d, 0xb1, 0x2d, 0xcd, 0xc1, 0x21, 0xc2, 0xca, 0xdb, 0x1d, 0xe9,
	0x95, 0x7c, 0x16, 0x8d, 0x0d, 0x9c, 0x8f, 0x94, 0x86, 0xe8, 0x38, 0xbb, 0xe0, 0x75, 0x29, 0x4f,
	0xcb, 0xa8, 0x7d, 0x85, 0xf5, 0x1f, 0x44, 0xe2, 0xe0, 0x13, 0xfd, 0xce, 0x61, 0x7b, 0xe0, 0xa8,
	0x8d, 0xe8, 0x45, 0xa7, 0x3a, 0xea, 0xdc, 0x40, 0x3d, 0x58, 0xce, 0x53, 0xa4, 0x51, 0x68, 0x6a,
	0xf3, 0xef, 0xef, 0x1f, 0x01, 0x9e, 0xed, 0xfe, 0x85, 0xe2, 0x97, 0x1b, 0x08, 0xef, 0xa0, 0x9a,
	0x7b, 0xf0, 0xaa, 0xe3, 0xbe, 0x3b, 0x5a, 0x7c, 0x83, 0xcb, 0x68, 0xc6, 0x68, 0x4f, 0xfa, 0x4a,
	0x6e, 0xf5, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x07, 0x3e, 0x96, 0x79, 0x3e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayServiceClient is the client API for PayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayServiceClient interface {
	Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error)
}

type payServiceClient struct {
	cc *grpc.ClientConn
}

func NewPayServiceClient(cc *grpc.ClientConn) PayServiceClient {
	return &payServiceClient{cc}
}

func (c *payServiceClient) Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error) {
	out := new(ChargeResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/Charge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayServiceServer is the server API for PayService service.
type PayServiceServer interface {
	Charge(context.Context, *ChargeRequest) (*ChargeResponse, error)
}

func RegisterPayServiceServer(s *grpc.Server, srv PayServiceServer) {
	s.RegisterService(&_PayService_serviceDesc, srv)
}

func _PayService_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).Charge(ctx, req.(*ChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PayService",
	HandlerType: (*PayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _PayService_Charge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pay.proto",
}
