// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pay.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChargeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeRequest) Reset()         { *m = ChargeRequest{} }
func (m *ChargeRequest) String() string { return proto.CompactTextString(m) }
func (*ChargeRequest) ProtoMessage()    {}
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{0}
}

func (m *ChargeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeRequest.Unmarshal(m, b)
}
func (m *ChargeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeRequest.Marshal(b, m, deterministic)
}
func (m *ChargeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeRequest.Merge(m, src)
}
func (m *ChargeRequest) XXX_Size() int {
	return xxx_messageInfo_ChargeRequest.Size(m)
}
func (m *ChargeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeRequest proto.InternalMessageInfo

func (m *ChargeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChargeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChargeRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChargeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ChargeResponse struct {
	Paid                 bool     `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Captured             bool     `protobuf:"varint,3,opt,name=captured,proto3" json:"captured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeResponse) Reset()         { *m = ChargeResponse{} }
func (m *ChargeResponse) String() string { return proto.CompactTextString(m) }
func (*ChargeResponse) ProtoMessage()    {}
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e5aad0ac58a7583, []int{1}
}

func (m *ChargeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeResponse.Unmarshal(m, b)
}
func (m *ChargeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeResponse.Marshal(b, m, deterministic)
}
func (m *ChargeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeResponse.Merge(m, src)
}
func (m *ChargeResponse) XXX_Size() int {
	return xxx_messageInfo_ChargeResponse.Size(m)
}
func (m *ChargeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeResponse proto.InternalMessageInfo

func (m *ChargeResponse) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *ChargeResponse) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeResponse) GetCaptured() bool {
	if m != nil {
		return m.Captured
	}
	return false
}

func init() {
	proto.RegisterType((*ChargeRequest)(nil), "proto.ChargeRequest")
	proto.RegisterType((*ChargeResponse)(nil), "proto.ChargeResponse")
}

func init() { proto.RegisterFile("proto/pay.proto", fileDescriptor_6e5aad0ac58a7583) }

var fileDescriptor_6e5aad0ac58a7583 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0x6d, 0x77, 0x59, 0x47, 0xac, 0x30, 0x54, 0x09, 0x3d, 0x2d, 0x7b, 0xea, 0xa9,
	0x82, 0x1e, 0xfc, 0x01, 0xe2, 0x51, 0x90, 0x9c, 0xbc, 0x8e, 0xcd, 0x50, 0x83, 0x34, 0x89, 0x49,
	0xf6, 0xd0, 0xb3, 0x7f, 0x5c, 0x9c, 0x54, 0xe9, 0x7a, 0xca, 0x7b, 0x2f, 0x43, 0xde, 0x97, 0x81,
	0xab, 0x10, 0x7d, 0xf6, 0xb7, 0x81, 0x0e, 0x1b, 0x51, 0xd8, 0xc8, 0x31, 0x7c, 0x55, 0x70, 0xf9,
	0xf8, 0x4e, 0x71, 0xc7, 0x9a, 0x3f, 0x47, 0x4e, 0x19, 0x17, 0x50, 0x5b, 0xa3, 0xaa, 0xbe, 0x5a,
	0xcf, 0x74, 0x6d, 0x0d, 0x2e, 0xa1, 0xc9, 0xfe, 0x83, 0x9d, 0xaa, 0xfb, 0x6a, 0x7d, 0xae, 0x8b,
	0xc1, 0x1b, 0x68, 0x69, 0xef, 0x47, 0x97, 0xd5, 0x4c, 0x26, 0x8f, 0x0e, 0x11, 0xe6, 0x8e, 0xf6,
	0xac, 0xe6, 0x32, 0x2c, 0x1a, 0x7b, 0xb8, 0x30, 0x9c, 0xb6, 0xd1, 0x86, 0x6c, 0xbd, 0x53, 0x8d,
	0x5c, 0x9d, 0x46, 0xc3, 0x2b, 0x2c, 0x7e, 0x21, 0x52, 0xf0, 0x2e, 0xf1, 0xcf, 0x3b, 0x81, 0x8e,
	0x1c, 0x9d, 0x16, 0x7d, 0xd2, 0x59, 0x4f, 0x3a, 0x57, 0xd0, 0x6d, 0x29, 0xe4, 0x31, 0xb2, 0x11,
	0x9a, 0x4e, 0xff, 0xf9, 0xbb, 0x27, 0x80, 0x17, 0x3a, 0x3c, 0x93, 0xa3, 0x1d, 0x47, 0x7c, 0x80,
	0xb6, 0xf4, 0xe0, 0xb2, 0xac, 0x61, 0x33, 0xf9, 0xfb, 0xea, 0xfa, 0x5f, 0x5a, 0x60, 0x86, 0xb3,
	0xb7, 0x56, 0xf2, 0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0x7a, 0xba, 0x68, 0x47, 0x01,
	0x00, 0x00,
}
